(("default" . ((user-emacs-directory . "~/.config/emacs")
               (env . (("DOOMDIR" . "~/.doom.d")))
               (server-name . "doom")))
 ("hackmode" . ((server-name . "hack")
                (user-emacs-directory . "~/Documents/Emacs/configs/hackmode/")
                (env . (("DOOMDIR" . "~/Documents/Emacs/configs/hackmode/doom")))))
 ("doomemacs" . ((server-name . "doom")
                 (user-emacs-directory . "~/.config/emacs")
                 (env . (("DOOMDIR" . "~/.doom.d")))))
 ("android" . ((server-name . "android")
               (user-emacs-directory . "~/Documents/Emacs/configs/android")))
 ("temple" . ((server-name . "temple")
              (user-emacs-directory . "~/Documents/Emacs/configs/android")
              (env . (("TEMPLE_MODE" . "active"))))))
