(("default" . ((user-emacs-directory . "~/.config/emacs")
               (env . (("DOOMDIR" . "~/.doom.d")))
               (server-name . "doom")))
 ("hackmode" . ((server-name . "hack")
                (user-emacs-directory . "~/.local/share/hackmacs/")))
 ("doomemacs" . ((server-name . "doom")
                 (user-emacs-directory . "~/.config/emacs")
                 (env . (("DOOMDIR" . "~/.doom.d")))))
 ("termux-doom" . ((server-name . "termux-doom")
                   (user-emacs-directory . "~/.config/emacs")
                   (env . (("DOOMDIR" . "~/.dotfiles/android/doom")))))
 ("android" . ((server-name . "android")
               (user-emacs-directory . "~/Documents/Emacs/configs/android")))
 ("temple" . ((server-name . "temple")
              (user-emacs-directory . "~/Documents/Emacs/configs/android")
              (env . (("TEMPLE_MODE" . "active"))))))
