#+TITLE: Readme

* Install dotfiles
clone repo  to ~/.dotfiles and run gnu stow .

* nix
** Setup nix
in .bashrc edit the $NIX_CONFIG to the path of the nixos config you wish to use

for example to use the desktop config

set NIX_CONFIG to
#+begin_src shell
NIX_CONFIG="desktop/desktop.nix"
#+end_src

By defualt its set to the desktop config.

** Evolve
`evolve` is a bash function to wrap the nixos rebuild switch so you config can stay in the ~/.dotfiles/ folder.

You can pass other options to it and it will be passed to it, by default it will just use the switch option.

* License
The MIT License (MIT)

Copyright (c) 2022

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
