;;; crew-test.el --- Crew protocol and actor tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'crew)
(defconst crew-test-root (file-name-directory (directory-file-name (file-name-directory (or load-file-name buffer-file-name)))))
(defmacro crew-test-state (&rest body)
  `(let ((crew-source-root crew-test-root)
         (crew--roles (make-hash-table :test #'eq)) (crew--teams (make-hash-table :test #'eq))
         (crew--members (make-hash-table :test #'equal)) (crew--requests (make-hash-table :test #'equal))
         (crew--serial 0) (crew--drain-timer nil) (crew--drain-offset 0)
         (opencode-workspace--agents (make-hash-table :test #'equal))
         (opencode-workspace--seen (make-hash-table :test #'equal))
         (opencode-workspace--epoch 0) (opencode-workspace--turns 0)
         (opencode-workspace-buffer-prefix "crew-test:"))
     (unwind-protect (progn ,@body)
       (when (timerp crew--drain-timer) (cancel-timer crew--drain-timer))
       (dolist (buffer (buffer-list))
         (when (string-prefix-p "*crew-test:" (buffer-name buffer)) (kill-buffer buffer))))))
(defun crew-test-define (&optional parallel budget)
  (defcrew-role researcher :goal "Research using evidence" :skills nil :experts nil
    :capabilities '("workspace.read" "crew.spawn" "crew.message") :delegates '(researcher reviewer))
  (defcrew-role reviewer :goal "Review independently" :skills nil :experts nil
    :capabilities '("workspace.read" "crew.message") :delegates nil)
  (crew-register 'test :project crew-test-root :model "fixture/model" :roles '(researcher reviewer)
                 :parallel (or parallel 8) :turn-budget (or budget 512)))
(defmacro crew-test-admit (&rest body)
  `(cl-letf (((symbol-function 'crew--policy) (lambda (_ cb) (funcall cb '((ok . t)))))
             ((symbol-function 'opencode-workspace--pump) (lambda (_) nil))) ,@body))
(ert-deftest crew-definitions-dont-launch ()
  (crew-test-state (crew-test-define) (should (= 0 (hash-table-count crew--members)))
   (should (= 0 (hash-table-count opencode-workspace--agents)))))
(ert-deftest crew-definitions-snapshot-roles ()
  (crew-test-state (crew-test-define)
   (crew-register-role 'researcher :goal "Changed")
   (should (equal "Research using evidence" (plist-get (crew--role (crew--team 'test) 'researcher) :goal)))))
(ert-deftest crew-has-many-instances-per-role ()
  (crew-test-state (crew-test-define)
   (crew-test-admit (crew-kickoff 'test 'researcher (make-list 40 "bounded task") 2))
   (should (= 40 (hash-table-count crew--members)))
   (should (= 432 (crew--team-remaining (crew--team 'test))))))
(ert-deftest crew-child-debits-parent-not-new-budget ()
  (crew-test-state (crew-test-define)
   (crew-test-admit
    (crew-spawn 'test 'researcher "root" :turns 10)
    (crew-spawn 'test 'reviewer "child" :parent "crew-test-1" :turns 4))
   (should (= 6 (crew--member-remaining (gethash "crew-test-1" crew--members))))
   (should (= 502 (crew--team-remaining (crew--team 'test))))
   (should (equal "crew-test-1" (crew--member-parent (gethash "crew-test-2" crew--members))))))
(ert-deftest crew-proposals-recheck-shared-snapshot ()
  (crew-test-state (crew-test-define) (let (callbacks)
   (cl-letf (((symbol-function 'crew--policy) (lambda (_ cb) (push cb callbacks)))
             ((symbol-function 'opencode-workspace--pump) (lambda (_) nil)))
     (crew-spawn 'test 'researcher "first") (crew-spawn 'test 'researcher "second")
     (funcall (cadr callbacks) '((ok . t))) (funcall (car callbacks) '((ok . t))))
   (should (= 1 (hash-table-count crew--members))))))
(ert-deftest crew-cancellation-cascades-preserving-members ()
  (crew-test-state (crew-test-define)
   (crew-test-admit
    (crew-spawn 'test 'researcher "root" :turns 10)
    (crew-spawn 'test 'reviewer "child" :parent "crew-test-1" :turns 4))
   (crew-cancel "crew-test-1")
   (should (= 2 (hash-table-count crew--members)))
   (dolist (m (hash-table-values crew--members)) (should (crew--member-cancelled m)))))
(ert-deftest crew-stop-fences-pending-admission ()
  (crew-test-state (crew-test-define) (let (callback)
   (cl-letf (((symbol-function 'crew--policy) (lambda (_ cb) (setq callback cb))))
     (crew-spawn 'test 'researcher "pending") (crew-stop 'test) (funcall callback '((ok . t))))
   (should (= 0 (hash-table-count crew--members))))))
(ert-deftest crew-unknown-protocol-is-rejected ()
  (crew-test-state (should-error (crew--receive #'ignore '((protocol . "ZARA-CREW/99"))))))
(ert-deftest crew-phase-is-prolog-gated-and-explicit ()
  (crew-test-state (crew-test-define)
   (cl-letf (((symbol-function 'crew--policy) (lambda (_ cb) (funcall cb '((ok . :false))))))
     (crew-advance 'test '((artifact . "a") (verified . t)) #'ignore))
   (should (eq 'research (crew--team-phase (crew--team 'test))))))
(ert-deftest crew-role-phase-restriction ()
  (crew-test-state
   (defcrew-role implementer :goal "Implement" :phases '(develop))
   (defcrew test :project crew-test-root :model "fixture/model" :roles '(implementer))
   (should-error (crew-spawn 'test 'implementer "not yet"))))
(ert-deftest crew-parallel-cap-and-remaining-turns ()
  (crew-test-state (crew-test-define 2)
   (crew-test-admit (crew-kickoff 'test 'researcher '("a" "b" "c" "d") 2))
   (dolist (w (hash-table-values opencode-workspace--agents))
     (crew--pump (lambda (worker) (setf (opencode-workspace-worker-state worker) 'running)) w))
   (should (= 2 (crew--running (crew--team 'test))))))
(ert-deftest crew-real-prolog-admission-roundtrip ()
  (crew-test-state (crew-test-define)
   (let ((crew-policy-program (or (executable-find "swipl") (ert-fail "SWI-Prolog required")))
         (done nil) result)
     (crew--policy (crew--spawn-context (crew--team 'test) 'researcher nil 4)
                   (lambda (answer) (setq result answer done t)))
     (let ((deadline (+ (float-time) 7)))
       (while (and (not done) (< (float-time) deadline)) (accept-process-output nil .05)))
     (should done) (should (eq t (alist-get 'ok result))))))

(ert-deftest crew-real-prolog-contract-matches-client ()
  (crew-test-state
   (let ((crew-policy-program (or (executable-find "swipl") (ert-fail "SWI required")))
         (done nil) result)
     (crew--policy '((op . "contract")) (lambda (answer) (setq result answer done t)))
     (let ((deadline (+ (float-time) 7)))
       (while (and (not done) (< (float-time) deadline)) (accept-process-output nil .05)))
     (should done)
     (should (equal crew-protocol (alist-get 'protocol result)))
     (should (equal (mapcar #'symbol-name crew--phases) (alist-get 'phases result))))))
