#+title: Doom Emacs configuration
#+author: nsaspy

#+property: header-args :emacs-lisp tangle: ./config.el :tangle yes :results none
#+startup: org-startup-folded: showall
#+disable_spellchecker: t
#+begin_src emacs-lisp;; -*- lexical-binding: t -*-
#+end_src
* About
This is my personal doom emacs config, you can find package related stuff in packages.org
yasnippets are in snippets


* Multi Platform config
Stuff to determin os and apply settings to fit that system


#+begin_src emacs-lisp
(defvar nsaspy/system "desktop"
        "platform name to base config for.
        it will load the name from ~/.platform")

(defun nsaspy/load-platform (path)
  "load the paatform name from file"
  (with-temp-buffer
    (insert-file-contents path)
    (buffer-string)))
#+end_src
* Styling
** Theme
I like doom's outrun electric theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-outrun-electric)
#+end_src

** Line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src
** Frame resize
This might help for wm like qtile
#+begin_src emacs-lisp
(setq frame-resize-pixelwise t)
#+end_src

Resize frames along the golden ratio
** Fonts
Setting nerdfonts
#+begin_src emacs-lisp
(setq
 doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 12)
 doom-big-font (font-spec :family "JetBrainsMono Nerd Font" :size 18)
 doom-variable-pitch-font (font-spec :family "JetBrainsMono Nerd Font" :size 12)
 doom-serif-font (font-spec :family "JetBrainsMono Nerd Font" :size 12))
#+end_src
* Packages
** Magit
Set keybinds for pushing to remote
Pushes the current branch to the remote
(eg: local master > remote master)
#+begin_src emacs-lisp
(map! :leader
      :desc "Push Current branch to remote branch"
      "g p P" #'magit-push-current-to-pushremote)
#+end_src

Same as above but for pulling from remote
#+begin_src emacs-lisp
(map! :leader
      :desc "Pull current branch from remote"
      "g p p" #'magit-pull-from-pushremote)
#+end_src

Create a new tag
#+begin_src emacs-lisp
(map! :leader
      :map 'magit-mode-map
      (:prefix-map ("g" . "git")
       (:prefix ("c" . "create")
      :desc "Create new git tag" "t" #'magit-tag-create)))

#+end_src
*** Magit Todos
Show todos!
#+begin_src emacs-lisp
(require 'magit-todos)
#+end_src
** Projectile
Setting the path to find projects
I store my stuff in ~/Documents/Projects
#+begin_src emacs-lisp
(setq projectile-project-search-path
      '(("~/Documents/Projects" . 1)))
#+end_src

** Org Mode
Setting org dir
#+begin_src emacs-lisp
(setq org-directory "~/Documents/Notes/org")
#+end_src

Source: https://org-roam.discourse.group/t/update-a-field-last-modified-at-save/321
i needed this to keep track of when i modify an org roam file so when i export it the times are correct.

#+begin_src emacs-lisp
(setq time-stamp-active t
      time-stamp-start "#\\+LAST_MODIFIED:[ \t]*"
      time-stamp-end "$"
      time-stamp-format "\[%Y-%02m-%02d %3a %02H:%02M\]")
(add-hook 'before-save-hook 'time-stamp nil)
#+end_src
*** org capture
Ask me where to place a capture at [[https://stackoverflow.com/a/24787118][source.]]
#+begin_src emacs-lisp
(defun org-ask-location ()
  (let* ((org-refile-targets '((nil :maxlevel . 9)))
         (hd (condition-case nil
                 (car (org-refile-get-location nil nil t t))
               (error (car org-refile-history)))))
    (goto-char (point-min))
    (outline-next-heading)
    (if (re-search-forward
         (format org-complex-heading-regexp-format (regexp-quote hd))
         nil t)
        (goto-char (point-at-bol))
      (goto-char (point-max))
      (or (bolp) (insert "\n"))
      (insert "* " hd "\n")))
    (end-of-line))
#+end_src
**** Org Capture Templates
i just dont want private shit being in here...

Here i override the capture templates, some intergrating into org roam
#+begin_src emacs-lisp

(setq  org-capture-templates (quote (("m" "Personal Meditations")
                                     ("mm" "Meditations Moon" entry
                                      (file+olp+datetree "~/Documents/Notes/org/moon.org")
                                      "** Relections\n\n*** Acomplished\n\n*** Thoughts\n\n*** Happenings\n\n** Plans for next moon\n" :tree-type month)
                                     ("t" "Personal todo" entry
                                      (file+headline +org-capture-todo-file "Inbox")
                                      "* [ ] %?\n%i\n%a" :prepend t)
                                     ("n" "Personal notes" entry
                                      (file+headline +org-capture-notes-file "Inbox")
                                      "* %u %?\n%i\n%a" :prepend t)
                                     ("j" "Journal" entry
                                      (file+olp+datetree +org-capture-journal-file)
                                      "* %U %?\n%i\n%a" :prepend t)
                                     ("p" "Templates for projects")
                                     ("pt" "Project-local todo" entry
                                      (file+headline +org-capture-project-todo-file "Inbox")
                                      "* TODO %?\n%i\n%a" :prepend t)
                                     ("pn" "Project-local notes" entry
                                      (file+headline +org-capture-project-notes-file "Inbox")
                                      "* %U %?\n%i\n%a" :prepend t)
                                     ("pc" "Project-local changelog" entry
                                      (file+headline +org-capture-project-changelog-file "Changelog")
                                      "* %U %?\n%i\n%a" :prepend t)
                                     ("o" "Centralized templates for projects")
                                     ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
                                     ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
                                     ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t)
                                     ("i" "Ideas Box" entry (file+headline "~/Documents/Notes/org/ideas.org" "Ideas")
                                      "* IDEA %? %^g"))))

#+end_src
*** Org Agenda
Find all TODOS recursively [[https://stackoverflow.com/a/41969519][source]].
#+begin_src emacs-lisp
(setq org-agenda-files (directory-files-recursively "~/Documents/Notes/org/agenda/" "\\.org$"))
;(dolist (file (directory-files-recursively "~/Documents/Notes/org/roam/" "\\.org$"))
;  (add-to-list org-agenda-files file))
#+end_src

#+begin_src emacs-lisp
(defun org-agenda-update-files ()
  "Update the org-agenda-files"
  (interactive)
  (setq org-agenda-files (directory-files-recursively "~/Documents/Notes/org/agenda" "\\.org$")))
(map! :leader
      :desc "update agenda"
      "o a u" #'org-agenda-update-files)
#+end_src

Track a org file by adding it to the agenda folder
#+begin_src emacs-lisp
(defun track-org-file ()
  "Create a symbolic link to the current file in the 'agenda' directory."
  (interactive)
  (let ((current-file (buffer-file-name)))
    (when current-file
      (make-symbolic-link current-file "~/Documents/Notes/org/agenda/")
      (setq org-agenda-files (directory-files-recursively "~/Documents/Notes/org/agenda/" "\\.org$")))))

(map! :after org
      :localleader
      :map org-mode-map
      :desc "Add file to Org agenda" "w" #'track-org-file)
#+end_src

I prefer being able to have different views within org agenda, so i can see whats coming up ahead of time.
#+begin_src emacs-lisp
(map! :leader
      :desc "Switch to week view"
      "o a w" #'org-agenda-week-view)

(map! :leader
      :desc "switch to month view"
      "o a m" #'org-agenda-month-view)

(map! :leader
      :desc "switch to month view"
      "o a y" #'org-agenda-year-view)
#+end_src



**** Org super agenda
#+begin_src emacs-lisp
(setq org-super-agenda-groups
      '(
        (:and (:todo "IDEA" :name "Starintel Idea" :tag ("starintel" "sit")) :name "Starintel ideas")
        (:and (:todo "TODO" :name "Starintel Bugs" :tag ("starintel-bug" "sib")) :name "Star intel Bugs")
        (:and (:todo "TODO" :name "Starintel" :tag ("starintel")) :name "Star Intel")
        (:and (:todo "TODO" :name "Personal" :tag ("mow" "trash" "personal")) :name "Personal")
        (:and (:todo "TODO" :name "Emacs" :tag ("emacs")) :name "Emacs")
        (:and (:todo "TODO" :name "Read inbox" :tag ("book" "artical" "books")) :name "Reading")))
#+end_src

*** Babel
Tangle a file
#+begin_src emacs-lisp
(map! :leader
      :desc "Tangle a file"
      "b t" #'org-babel-tangle)
#+end_src

Execute the selected source block (used for literate programming)
#+begin_src emacs-lisp
(map! :leader
      :desc "Babel execute selected source block"
      "c b" #'org-babel-execute-src-block)
#+end_src

Execute all src blocks in buffer
#+begin_src emacs-lisp
(map! :leader
      :desc "Babel execute buffer"
      "c B" #'org-babel-execute-buffer)
#+end_src

Add languages to org babel

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t) (org . t) (nim . t) (python . t) (erlang . t) (ein . t) (lisp . t)))
#+end_src

**** Better Formating in org-babel
Adapted from [[https://www.reddit.com/r/emacs/comments/9tp79o/comment/e90g7km/?utm_source=share&utm_medium=web2x&context=3][here]].
#+begin_src emacs-lisp
(defun edit-src-block (src fn language)
  "Replace SRC org-element's value property with the result of FN.
FN is a function that operates on org-element's value and returns a string.
LANGUAGE is a string referring to one of orb-babel's supported languages.
(https://orgmode.org/manual/Languages.html#Languages)"
  (let ((src-language (org-element-property :language src))
        (value (org-element-property :value src)))
    (when (string= src-language language)
      (let ((copy (org-element-copy src)))
        (org-element-put-property copy :value
                                  (funcall fn value))
        (org-element-set-element src copy)))))

(defun format-elisp-string (string)
  "Indents elisp buffer string and reformats dangling parens."
  (with-temp-buffer
    (let ((inhibit-message t))
      (emacs-lisp-mode)
      (insert
       (replace-regexp-in-string "[[:space:]]*
[[:space:]]*)" ")" string))
      (indent-region (point-min) (point-max))
      (buffer-substring (point-min) (point-max)))))

(defun format-elisp-src-blocks ()
  "Format Elisp src blocks in the current org buffer"
  (interactive)
  (save-mark-and-excursion
    (let ((AST (org-element-parse-buffer)))
      (org-element-map AST 'src-block
        (lambda (element)
          (edit-src-block element #'format-elisp-string "emacs-lisp")))
      (delete-region (point-min) (point-max))
      (insert (org-element-interpret-data AST)))))

(map! :leader
      :after org
      :prefix ("b" . "org-babel-fomats")
      :desc "format src" "f" #'format-elisp-src-blocks)
#+end_src


**** LSP with org-babel
[[https://github.com/emacs-lsp/lsp-mode/issues/2842#issuecomment-870807018][Source]]
***** Python
#+begin_src emacs-lisp
(defun org-babel-edit-prep:python (babel-info)
  (setq-local buffer-file-name (->> babel-info caddr (alist-get :tangle)))
  (lsp))
#+end_src

***** Nim
#+begin_src emacs-lisp
(defun org-babel-edit-prep:nim (babel-info)
  "Setup for lsp-mode in Org Src buffer using BABEL-INFO."
  (setq-local default-directory (->> babel-info caddr (alist-get :dir)))
  (setq-local buffer-file-name (->> babel-info caddr (alist-get :tangle)))
  (lsp))
#+end_src

***** Bash
#+begin_src emacs-lisp
(defun org-babel-edit-prep:sh (babel-info)
  (setq-local buffer-file-name (->> babel-info caddr (alist-get :tangle)))
  (lsp))
#+end_src


*** Org Tempo templates
I experiment with different languages, org babel makes things easy.
#+begin_src emacs-lisp
(with-eval-after-load 'org
  ;; is needed as of Org 9.2
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("php" . "src php"))
  (add-to-list 'org-structure-template-alist '("jn" . "src json"))
  (add-to-list 'org-structure-template-alist '("xm" . "src xml"))
  (add-to-list 'org-structure-template-alist '("js" . "src js"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("nim" . "src nim"))
  (add-to-list 'org-structure-template-alist '("erl" . "src erlang"))
  (add-to-list 'org-structure-template-alist '("ss" . "src scheme"))
  (add-to-list 'org-structure-template-alist '("cl" . "src common-lisp"))
  (add-to-list 'org-structure-template-alist '("nix" . "src nix")))
#+end_src

*** Org config sync
Create a function to tangle and sync doom at the same time
#+begin_src emacs-lisp
(defvar org-configs-list ()
  "A List of org documents that holds your configuration. Will be used to tangle to elisp")
(setq org-configs-list '("~/.doom.d/config.org" "~/.doom.d/packages.org"))
(defun tangle-orgs (config-list)
  "Tangle a list of org documents."
  (mapcar 'org-babel-tangle-file config-list))

(defun doom-config-sync ()
  "Tangle your dotfiles and run doom sync"
  (interactive)
  (tangle-orgs org-configs-list)
  (doom/reload))

#+end_src
*** org-download
This extension facilitates moving images from point A to point B.

#+begin_src emacs-lisp
(require 'org-download)

;; Drag-and-drop to `dired`
;;(add-hook 'dired-mode-hook 'org-download-enable)
#+end_src


Configure keybinds. this will be under `SPC m a `
#+begin_src emacs-lisp
(map! :localleader
      :after org
      :map org-mode-map
      :prefix ("a" . "attachments")
      :desc "paste image" "p" #'org-download-clipboard
      :desc "insert image from url" "i" #'org-download-yank)
#+end_src


*** Org Roam
A Personal wiki

Set roam directory
#+begin_src emacs-lisp
(setq org-roam-directory "~/Documents/Notes/org/roam")
#+end_src

#+begin_src emacs-lisp
;;  Tahnk you, this comment fixed my old config!
;;  https://www.reddit.com/r/DoomEmacs/comments/sk8558/comment/hxxp7l0/?utm_source=share&utm_medium=web2x&context=3

(after! org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  (setq org-roam-directory "~/Documents/Notes/org/roam")
  (setq org-roam-complete-everywhere t)
  (setq org-roam-capture-templates
        '(
          ("d" "default" plain "%?"
           :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n") :unnarrowed t)
          ("t" "tutorial" plain "*%?"
           :target (file+head "Tutorial/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("h" "hacking" plain "%?"
           :target (file+head "hacking/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("s" "star intel" plain "*%? %^g"
           :target (file+head "starintel/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("d" "sunshine wiki dox" plain "* {slug}\n%?"
           :target (file+head "starintel/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("r" "Reading notes" plain "%?"
           :target (file+head "reading-notes/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("v" "Video notes" plain "%?"
           :target (file+head "reading-notes/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))
          ("p" "Programming" plain "%?"
           :target (file+head "programming/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+TITLE: ${title}\n#+CREATED: %U\n#+LAST_MODIFIED: %U\n\n"))))
   (setq org-roam-dailies-capture-templates
   '(("d" "default" entry "* %<%I:%M %p>: %?"
      :target (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))
     ("n" "news" entry "* %? :news:"
         :target (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))
     ("j" "journal" entry "* %<%I:%M %p>%? :personal:"
        :target (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")))))
#+end_src

*** Misc org roam
url2org function for importing info from the web

#+begin_src emacs-lisp
(defun url2org (begin end)
  "Download a webpage from selected url and convert to org."
  (interactive "r")
  (shell-command-on-region begin end
                           (concat "pandoc --from=html --to=org " (buffer-substring begin end))
                           nil t))
#+end_src


For some reason caching on write isnt working.
If my notes get slow i will disable it.
*** Org File Encryption

Eyes off my doccuments
#+begin_src emacs-lisp
(require 'epa-file)
(epa-file-enable)
#+end_src

#+begin_src emacs-lisp
(setq epa-file-encrypt-to '("nsaspy@airmail.cc"))
#+end_src

#+begin_src emacs-lisp
(setq epa-file-select-keys "235327FBDEFB3719")
#+end_src

*** Org Pomodoro
#+begin_src emacs-lisp
(map! :localleader
      :after org
      :map org-mode-map
      :prefix ("c" . "clock")
      :desc "Start Pomodoro" "T" #'org-pomodoro)
#+end_src

*** Org Present
Create presentations with org mode


Thanks to systems crafters for the prebaked config!
https://www.youtube.com/watch?v=SCPoF1PTZpI
Go sub to him if you havent hes worth your time.
#+begin_src emacs-lisp
;; Hide emphasis markers on formatted text
(setq org-hide-emphasis-markers t)
;;; Centering Org Documents --------------------------------
;; Configure fill width
(setq visual-fill-column-width 180
      visual-fill-column-center-text t)

;;; Org Present --------------------------------------------

;; Install org-present if needed

(defun my/org-present-prepare-slide (buffer-name heading)
  ;; Show only top-level headlines
  (org-overview)

  ;; Unfold the current entry
  (org-show-entry)

  ;; Show only direct subheadings of the slide but don't expand them
  (org-show-children))

(defun my/org-present-start ()
  ;; Tweak font sizes
  (doom-big-font-mode)
  (org-present-read-only)
  (org-present-hide-cursor)
  ;; Set a blank header line string to create blank space at the top
  (setq header-line-format " ")
  ;; Hide line numbers
  (setq-local display-line-numbers nil)
  ;; Display inline images automatically
  (org-display-inline-images)

  ;; Center the presentation and wrap lines
  (visual-fill-column-mode 1)
  (visual-line-mode 1))

(defun my/org-present-end ()
  ;; Reset font customizations
  (doom-big-font-mode)
  ;; Clear the header line string so that it isn't displayed
  (setq header-line-format nil)
  ;; Shone line numbers
  (setq-local display-line-numbers t)
  ;; Stop displaying inline images
  (org-remove-inline-images)
  (org-present-read-write)
  (org-present-show-cursor))
  ;; Stop centering the document


;; Turn on variable pitch fonts in Org Mode buffers
;(add-hook! 'org-mode variable-pitch-mode)

;; Register hooks with org-present
(add-hook 'org-present-mode-hook 'my/org-present-start)
(add-hook 'org-present-mode-quit-hook 'my/org-present-end)
(add-hook 'org-present-after-navigate-functions 'my/org-present-prepare-slide)
#+end_src


*** Org Idea box
Keep my ideas seperated from my todos and give me a random idea from the file

*** Misc related functions for org mode
****  Time Stamp updater
#+begin_src emacs-lisp
(defun update-timestamps (directory)
  "Update timestamps in all org files in DIRECTORY."
  (interactive "DDirectory: ")
  (let ((files (directory-files-recursively directory "\\.org$")))
    (dolist (file files)
      (with-current-buffer (find-file-noselect file)
        (save-excursion
          (goto-char (point-min))
          (time-stamp))))))

(defun update-timestamps-in-directory (directory)
  "Update timestamps in all org files in DIRECTORY."
  (let ((files (directory-files-recursively directory "\\.org$")))
    (dolist (file files)
      (with-current-buffer (find-file-noselect file)
        (save-excursion
          (goto-char (point-min))
          (time-stamp))))))

#+end_src
**** Get Tags from headlines :ai:
#+begin_src emacs-lisp

#+end_src

***
** Deft
Deft is used for notes. here im setting the default directory
#+begin_src emacs-lisp
(setq deft-extenstions '("txt", "org", "md"))
(setq deft-directory "~/Documents/Notes")
#+end_src

Deft is not recursive by defualt (it will not go into sub directories)
#+begin_src emacs-lisp
(setq deft-recursive t)
#+end_src
Tell deft to use the filename as the Title of the note
#+begin_src emacs-lisp
(setq deft-use-filename-as-title t)
#+end_src

** Notifications
*** Emacs built in notifications
#+begin_src emacs-lisp
(require 'notifications)
#+end_src

** RSS (Elfeed)
#+begin_src emacs-lisp
(require 'elfeed-org)
#+end_src
Hook elfeed-org to elfeed
#+begin_src emacs-lisp
(elfeed-org)
#+end_src

Tell elfeed where to look for org mode files

#+begin_src emacs-lisp
(setq rmh-elfeed-org-files '("~/Documents/Notes/org/rss.org"))
#+end_src


** Web-paste
Web-paste allows you to paste text to pastebin like web services
#+begin_src emacs-lisp
(require 'webpaste)
#+end_src

Tell Web-paste to confirm before upload
#+begin_src emacs-lisp
(setq webpaste-paste-confirmation t)
#+end_src

Provider priority
#+begin_src emacs-lisp
(setq webpaste-provider-priority '("ix.io" "dpaste.org"
                                   "dpaste.com" "clbin.com"
                                   "0x0.st" "bpa.st"
                                   "paste.rs"))
#+end_src

Setting Key binds
#+begin_src emacs-lisp
(map! :leader
      (:prefix-map ("n" . "notes")
       (:prefix ("p" . "webpaste")
        :desc "paste region to a paste service" "r" #'webpaste-paste-region
        :desc "paste entire buffer to paste service" "b" #'webpaste-paste-buffer)))
#+end_src

** Pcap mode
You can view a pcap file with tshark

#+begin_src emacs-lisp
(require 'pcap-mode)
#+end_src

** inherit org
inherit-org: Inherit org faces to non-org buffers.
#+begin_src emacs-lisp

(with-eval-after-load 'org
  (require 'inherit-org)
; BUG something is wrong with spc h f on nixos, works on arch
  (with-eval-after-load 'info
    (add-hook 'Info-mode-hook 'inherit-org-mode))

  (with-eval-after-load 'helpful
    (add-hook 'helpful-mode-hook 'inherit-org-mode))

  (with-eval-after-load 'w3m
    (add-hook 'w3m-fontify-before-hook 'inherit-org-w3m-headline-fontify) ;only one level is supported
    (add-hook 'w3m-fontify-after-hook 'inherit-org-mode)))
#+end_src

** W3M

fix text area
#+begin_src emacs-lisp
(eval-after-load "w3m-form"
  '(progn
     (define-minor-mode dme:w3m-textarea-mode
       "Minor mode used when editing w3m textareas."
       nil " dme:w3m-textarea" w3m-form-input-textarea-keymap)
     (defun dme:w3m-textarea-hook ()
                                        ; protect the form local variables from being killed by `text-mode'
       (mapcar (lambda (v)
		 (if (string-match "^w3m-form-input-textarea.*"
				   (symbol-name (car v)))
		     (put (car v) 'permanent-local t)))
	       (buffer-local-variables))
       (text-mode)
       (dme:w3m-textarea-mode))
     (add-hook! 'w3m-form-input-textarea-mode-hook 'dme:w3m-textarea-hook)))
#+end_src

** Vterm
its a good term

set the window title
#+begin_src emacs-lisp
(defun vterm--rename-buffer-as-title (title)
  (let ((dir (string-trim-left (concat (nth 1 (split-string title ":")) "/"))))
    (cd-absolute dir)
    (rename-buffer (format "term %s" title))))
(add-hook 'vterm-set-title-functions 'vterm--rename-buffer-as-title)
#+end_src

** Dirvish
a better dired
#+begin_src emacs-lisp
(require 'dirvish)
(dirvish-override-dired-mode)
#+end_src

#+begin_src emacs-lisp
(use-package! dirvish
  :init
  (dirvish-override-dired-mode)
  :custom
  (dirvish-quick-access-entries ; It's a custom option, `setq' won't work
   '(("h" "~/"                          "Home")
     ("d" "~/Downloads/"                "Downloads")
     ("m" "/mnt/"                       "Drives")
     ("t" "~/.local/share/Trash/files/" "TrashCan")))
  :config
  ;; (dirvish-peek-mode) ; Preview files in minibuffer
  ;; (dirvish-side-follow-mode) ; similar to `treemacs-follow-mode'
  (setq dirvish-mode-line-format
        '(:left (sort symlink) :right (omit yank index)))
  (setq dirvish-attributes
        '(all-the-icons file-time file-size collapse subtree-state vc-state git-msg))
  (setq delete-by-moving-to-trash t)
  (setq dired-listing-switches
        "-l --almost-all --human-readable --group-directories-first --no-group")
  :bind ; Bind `dirvish|dirvish-side|dirvish-dwim' as you see fit
  (("C-c f" . dirvish-fd)
   :map dirvish-mode-map ; Dirvish inherits `dired-mode-map'
   ("a"   . dirvish-quick-access)
   ("f"   . dirvish-file-info-menu)
   ("y"   . dirvish-yank-menu)
   ("N"   . dirvish-narrow)
   ("^"   . dirvish-history-last)
   ("h"   . dirvish-history-jump) ; remapped `describe-mode'
   ("s"   . dirvish-quicksort)    ; remapped `dired-sort-toggle-or-edit'
   ("v"   . dirvish-vc-menu)      ; remapped `dired-view-file'
   ("TAB" . dirvish-subtree-toggle)
   ("M-f" . dirvish-history-go-forward)
   ("M-b" . dirvish-history-go-backward)
   ("M-l" . dirvish-ls-switches-menu)
   ("M-m" . dirvish-mark-menu)
   ("M-t" . dirvish-layout-toggle)
   ("M-s" . dirvish-setup-menu)
   ("M-e" . dirvish-emerge-menu)
   ("M-j" . dirvish-fd-jump)))
#+end_src
** Libraries :lib::programming::lisp:
*** f.el :lisp:
Much inspired by @magnarss excellent s.el and dash.el, f.el is a modern API for working with files and directories in Emacs.
#+begin_src emacs-lisp
(require 'f)
#+end_src
*** dash.el :lisp:
A modern list API for Emacs. No 'cl required.

#+begin_src emacs-lisp
(require 'dash)
#+end_src
*** s.el :lisp:
The long lost Emacs string manipulation library.
#+begin_src emacs-lisp
(require 's)
#+end_src

* Programming

This section would not fit well, therefor it is in its own.

** Python

Set the exec path for pyright
#+begin_src emacs-lisp
(setq lsp-package-path (executable-find "pyright"))
#+end_src
** Direnv
Make life easy!
#+begin_src emacs-lisp
(envrc-global-mode)
#+end_src

** Nix
Nix is a language that allows for reproducible declarative systems/packages.

Search nixos options so i don't have to go the website
#+begin_src emacs-lisp
(map! :leader
      :after nix
      :map nix-mode-map
      :prefix ("s" . "search")
      :desc "search option" "n" #'helm-nixos-options)
#+end_src

Update the rev and sha of a fetchgit package

#+begin_src emacs-lisp
(require 'nix-update)
(map! :localleader
      :after nix
      :map nix-mode-map
      :prefix ("u" . "update")
      :desc "Update fetchgit" "g" #'nix-update-fetch)

#+end_src
add nix-options to company backends
#+begin_src emacs-lisp
(add-to-list 'company-backends 'company-nixos-options)

#+end_src

#+begin_src emacs-lisp
(setq flycheck-command-wrapper-function
        (lambda (command) (apply 'nix-shell-command (nix-current-sandbox) command))
      flycheck-executable-find
        (lambda (cmd) (nix-executable-find (nix-current-sandbox) cmd)))
#+end_src
** Nim
FlyCheck nim
Does this even do anything?
#+begin_src emacs-lisp
(require 'flycheck-nim)
#+end_src

hook lsp to nim lsp
[[https://gist.github.com/cyraxjoe/9001fcc5d2de0669d7e0d27f7a49ee90][source]], [[https://www.reddit.com/r/nim/comments/dr0ph0/setting_up_nimlsp_in_emacs/][reddit comment]].
#+begin_src emacs-lisp
(require 'lsp-mode)
(add-to-list 'lsp-language-id-configuration '(nim-mode . "nim"))
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "nimlsp")
                  :major-modes '(nim-mode)
                  :server-id 'nimlsp))
(add-hook 'nim-mode-hook #'lsp)
#+end_src


** Forth
Load forth mode
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.fs" . 'forth-mode))
#+end_src

** Flycheck
Check for errors!

#+begin_src emacs-lisp
(use-package! flycheck-package
  :after flycheck
  :config (flycheck-package-setup))
#+end_src

** Dumb Jump
When/If i leave doom ill need to configure it.
A Jump to definition package. [[https://github.com/jacktasia/dumb-jump][Github]].

Enable the xref back-end.
#+begin_src emacs-lisp
(add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
#+end_src
** Emacs Lisp

Add my own elisp dir to the load-path
#+begin_src emacs-lisp
(let ((default-directory (f-expand "~/.doom.d/lisp")))
  (normal-top-level))
#+end_src

* Misc
** Performance
Enable explain Pause mode

Alerts you when something takes some time (40ms)
disabled because I swear it causes me problems
#+begin_src emacs-lisp
(explain-pause-mode nil)
#+end_src

** Environment

Sets PATH
#+begin_src emacs-lisp
;;(when (memq window-system '(mac ns x))
;;  (exec-path-from-shell-initialize))
#+end_src
** Url proxy
I use i2p and having elfeed use a proxy would be nice
#+begin_src emacs-lisp
;(setq url-proxy-services
;   '(("no_proxy" . "^\\(localhost\\|10.*\\|\\.(?!i2p)[a-zA-Z0-9-]{1,255}$\\)")
;     ("http" . "127.0.0.1:4444")
;     ("https" . "127.0.0.1:4444")
;))
;(setq elfeed-use-curl nil)
#+end_src
** Cheat-sh
#+begin_src emacs-lisp
(defun cht-sh ()
  "look up a cheat"
  (interactive)
  (async-shell-command (format "cht.sh %s" (read-string "Enter search: "))))
(map! :leader
      :prefix ("s" . "search")
      :desc "cheat sheat" "c" #'cht-sh)
#+end_src


** Bookmarks
#+begin_src emacs-lisp
(setq bookmark-file "~/Documents/Emacs/bookmarks")
#+end_src

** Activity Watch
#+begin_src emacs-lisp
(global-activity-watch-mode)
#+end_src

** Games
Stuff that i use for games are here.

*** Kerbal Space Program
#+begin_src emacs-lisp
(require 'ks)
#+end_src
** Social Media
*** Mastodon.el
#+begin_src emacs-lisp
    (setq mastodon-instance-url "https://pleroma.nobodyhasthe.biz"
          mastodon-active-user "nott")

#+end_src

** Other
#+begin_src emacs-lisp
(use-package! org-pomodoro
  :init
  (setq org-pomodoro-audio-player "/usr/bin/mpv"))
#+end_src

** Spell check
Make sure its using aspell
#+begin_src emacs-lisp
(setq ispell-program-name "aspell")
#+end_src
Set dictionary
#+begin_src emacs-lisp
(setq ispell-dictionary "en")
#+end_src

Set personal dictionary
#+begin_src emacs-lisp
 (setq ispell-personal-dictionary "~/.aspell.en_us.pws")
#+end_src

Spell fu setup

#+begin_src emacs-lisp
(add-hook 'spell-fu-mode-hook
  (lambda ()
    (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "en"))
    (spell-fu-dictionary-add
      (spell-fu-get-personal-dictionary "en-personal" "~/.aspell.en_us.pws"))))
#+end_src
** Midnight mode
Clean up emacs overnight
require it
#+begin_src emacs-lisp
(require 'midnight)
#+end_src
Set the time to 7 am local
#+begin_src emacs-lisp
(midnight-delay-set 'midnight-delay "7:00am")
#+end_src

* Security
** Auth info source
Tell auth info to put authsource in my dotfiles
#+begin_src emacs-lisp
(setq auth-sources '("~/.authinfo.gpg")
      auth-source-cache-expiry nil)
#+end_src
