#+title: Doom Packages
#+author: nsaspy
#+property: header-args :emacs-lisp tangle: ./packages.el :tangle yes :results none
#+startup: org-startup-folded: overview
#+disable_spellchecker: t
#+begin_src emacs-lisp
;; -*- lexical-binding: t -*-
#+end_src

#+begin_src emacs-lisp
;;; Package management

;; Please don't load outdated byte code
;(setq load-prefer-newer t)

(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives
      ;; Package archives
      '(("MELPA Stable" . "https://stable.melpa.org/packages/") ("MELPA" . "https://melpa.org/packages/"))
      ;; Prefer MELPA Stable over GNU over MELPA. IOW prefer MELPA's stable
      ;; packages over everything and only fall back to GNU or MELPA if ;; necessary.
      package-archive-priorities '(("MELPA Stable" . 10) ("GNU ELPA" . 5) ("MELPA" . 0))) (package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package) (package-refresh-contents) (package-install 'use-package))

;(eval-when-compile (require 'use-package))
#+end_src
* About
This org document contains all the packages that i install into emacs. I thought about merging it into config.org but that's just going to make a big mess. I will split it into sections and catogries of packages.

+ Config is here [[./config.org]]


* Org mode
** org-roam-ui
Org-Roam-UI is a front-end for exploring and interacting with your org-roam notes.
unpin org-roam.
#+begin_src emacs-lisp
(unpin! org-roam)
(package! org-roam-ui)
#+end_src
** org-ql
This package provides a query language for Org files. It offers two syntax styles: Lisp-like sexps and search engine-like keywords.
#+begin_src emacs-lisp
(package! org-ql :recipe (:type git :host github :repo "alphapapa/org-ql"))
#+end_src


** org-timed-alerts
Receive warnings and alerts via alert.el for upcoming events in your day.
#+begin_src emacs-lisp
(package! org-timed-alerts :recipe (:type git :host github :repo "legalnonsense/org-timed-alerts"))
#+end_src

** org-alert
Provides notifications for scheduled or deadlined agenda entries.
#+begin_src emacs-lisp
(package! org-alert)
#+end_src


** org-download
This extension facilitates moving images from point A to point B.

#+begin_src emacs-lisp
(package! org-download :recipe (:type git :host github :repo "abo-abo/org-download"))
#+end_src


** ox-hugo
export to hugo markdown
#+begin_src emacs-lisp
;; (package! ox-hugo)
#+end_src
** Org Modern
#+begin_src emacs-lisp
(package! org-modern)
#+end_src
** writeroom-mode
Distraction free writing.
#+begin_src emacs-lisp
(package! writeroom-mode)
#+end_src
** ob-http
#+begin_src emacs-lisp
(package! ob-http)
#+end_src

** org-recoll

#+begin_src emacs-lisp
(package! org-recoll :recipe (:type git :host github :repo "alraban/org-recoll"))
#+end_src


** Project tasks
Sysadmin/hackmode checklists with orgmode
#+begin_src emacs-lisp
(package! project-tasks :recipe (:type git :host github :repo "TxGVNN/project-tasks"))
#+end_src
** TODO Org Transclusion
Include notes from other notes!
#+begin_src emacs-lisp
;(package! org-transclusion)
#+end_src
** Org Drill
Create Flashcards from
#+begin_src emacs-lisp
(package! org-drill)
#+end_src

* AI
** transient
Current gptel requires a modern Transient.  Tracking it with gptel ensures
Dirvish and gptel are rebuilt against the same EIEIO class definitions.
#+begin_src emacs-lisp
(unpin! transient)
(package! transient :recipe (:host github :repo "magit/transient"))
#+end_src
** gptel
Interact with LLMs from Org mode and expose current tool, reasoning, Responses
API, and OpenAI subscription OAuth support.  Track upstream gptel instead of
Doom's older package pin.
#+begin_src emacs-lisp
(unpin! gptel)
(package! gptel
  :recipe (:host github :repo "karthink/gptel"
           :files ("*.el")))
#+end_src
** MCP Services
GPTEL supports MCP.
#+begin_src emacs-lisp
(package! mcp :recipe (:type git :host github :repo "lizqwerscott/mcp.el"))
#+end_src
* Development
** envrc
A GNU Emacs library which uses direnv to set environment variables on a per-buffer basis. This means that when you work across multiple projects which have .envrc files, all processes launched from the buffers "in" those projects will be executed in the context of that project's .envrc.
#+begin_src emacs-lisp
(package! envrc :recipe (:type git :host github :repo "purcell/envrc"))
#+end_src

** protobufs
#+begin_src emacs-lisp
;(package! protobuf-mode)
#+end_src

** Langauges
**** Nim lang
***** Nim Mode
Doom's Version is way too old.
#+begin_src emacs-lisp
;(unpin! nim-mode)
;(unpin! nim-mode :pin "1338e5b0d5e111ad932efb77d3cad680cc3b86c9")
#+end_src
***** flycheck-nim
Flycheck-nim is a syntax checker definition for Nim.
#+begin_src emacs-lisp
;;(package! flycheck-nim :recipe (:type git :host github :repo "ALSchwalm/flycheck-nim"))
#+end_src
***** ob-nim
#+begin_src emacs-lisp
(package! ob-nim :recipe (:type git :host github :repo "Lompik/ob-nim"))
#+end_src
**** gForth
major mode for gforth
<2023-11-07 Tue> Not removing this, just not using it for now.
#+begin_src emacs-lisp
;(package! gforth.el :recipe (:type git :host github :repo "smtlaissezfaire/gforth.el"))
#+end_src
***** nix
**** Python
#+begin_src emacs-lisp
(package! lsp-pyright :recipe (:type git :host github :repo "emacs-lsp/lsp-pyright"))
#+end_src

**** Lisp
#+begin_src emacs-lisp
(package! evil-smartparens)
#+end_src

**** Prolog
LOGIC!
***** ob-prolog
https://github.com/ljos/ob-prolog
Org babel functions for prolog.
#+begin_src emacs-lisp
(package! ob-prolog)
#+end_src


**** gnuplot
#+begin_src emacs-lisp
(package! gnuplot)
#+end_src
** Magit
*** Magit Todos
Show TODOs in Magit.
#+begin_src emacs-lisp
(package! magit-todos :recipe (:type git :host github :repo "alphapapa/magit-todos"))
#+end_src

* utilities
** Hack mode
Hack banks from emacs
jk, package full of utilities for pentesting
#+begin_src emacs-lisp
(package! hackmode :recipe (:type git :host github :repo "lost-rob0t/emacs-hackmode"))
#+end_src
** webpaste.el
paste your buffer to a pastebin like service.
#+begin_src emacs-lisp
(package! webpaste :recipe (:type git :host github :repo "etu/webpaste.el"))
#+end_src
** Burly
Save and restore frame and window configurations.
#+begin_src emacs-lisp
(package! burly :recipe (:type git :host github :repo "alphapapa/burly.el"))
#+end_src
** podman.el
Manage podman containers from Emacs.
#+begin_src emacs-lisp
(package! podman.el :recipe (:type git :host github :repo "akirak/podman.el"))
#+end_src

** pcap-mode.el
A major mode to view pcap files.
#+begin_src emacs-lisp
(package! pcap-mode.el :recipe (:type git :host github :repo "orgcandman/pcap-mode.el"))
#+end_src
** exec-path-from-shell
Import shell environment variables into Emacs.
#+begin_src emacs-lisp
(package! exec-path-from-shell  :recipe (:type git :host github :repo "purcell/exec-path-from-shell"))
#+end_src

** cheat-sh
Get cheatsheets.
#+begin_src emacs-lisp
(package! cheat-sh :recipe (:type git :host github :repo "davep/cheat-sh.el"))
#+end_src

** activity watch
Track time in Emacs.
#+begin_src emacs-lisp
(package! activity-watch-mode :recipe (:type git :host github :repo "pauldub/activity-watch-mode"))
#+end_src

** Discover
Context menus for discovering commands.
#+begin_src emacs-lisp
(package! discover :recipe (:type git :host github :repo "mickeynp/discover.el"))
#+end_src
** atomic-chrome
Edit browser text areas in Emacs.
#+begin_src emacs-lisp
(package! atomic-chrome)
#+end_src


** app-launcher
#+begin_src emacs-lisp
(package! app-launcher :recipe (:type git :host github :repo "SebastienWae/app-launcher"))
#+end_src

** yassnippets collection
#+begin_src emacs-lisp :tangle yes
(package! yasnippet-snippets)
#+end_src
** skeletor.el
#+begin_src emacs-lisp
(package! skeletor)
#+end_src
* Lib packages
** plz
HTTP library using curl.
#+begin_src emacs-lisp
(package! plz :recipe (:type git :host github :repo "alphapapa/plz.el"))
#+end_src

** dash
Modern list API.
#+begin_src emacs-lisp
(package! dash :recipe (:type git :host github :repo "magnars/dash.el"))
#+end_src
** s.el
String library.
#+begin_src emacs-lisp
(package! s :recipe (:type git :host github :repo "magnars/s.el"))
#+end_src
** alert
Send alerts.
#+begin_src emacs-lisp
(package! alert :recipe (:type git :host github :repo "jwiegley/alert"))
#+end_src
** f.el
Modern file API.
#+begin_src emacs-lisp
(package! f)
#+end_src
** Async
Async processing in Emacs.
#+begin_src emacs-lisp
(package! emacs-async :recipe (:type git :host github :repo "jwiegley/emacs-async"))
#+end_src

** jeison
Parse JSON declaratively.
#+begin_src emacs-lisp
;(package! jeison)
#+end_src
** org-contrib
#+begin_src emacs-lisp
(package! org-contrib)
#+end_src

** REGEX
Required by magit-todos.
#+begin_src emacs-lisp
(package! ppcre2el :recipe (:type git :host github :repo "joddie/ppcre2el"))
#+end_src

#+begin_src emacs-lisp
(package! rx)
#+end_src

** Starintel Deps
#+begin_src emacs-lisp
(package! asoc :recipe (:type git :host github :repo "troyp/asoc.el"))
#+end_src



* Messaging And media
** elfeed-tube
MPV+elfeed
#+begin_src emacs-lisp
(package! elfeed-tube)
#+end_src
* rice
** dirvish
a better dired
#+begin_src emacs-lisp
(package! dirvish :recipe (:host github :repo "alexluigit/dirvish"))
#+end_src


* System

** Libvirt
Manage virtual machines.
#+begin_src emacs-lisp
(package! libvirt :recipe (:type git :host github :repo "lost-rob0t/libvirt-el"))
#+end_src
* TODO Exwm
#+begin_src emacs-lisp
;(package! exwm)
#+end_src

** exwm-firefox-evil
Evil mode keys in firefox
#+begin_src emacs-lisp
;(package! exwm-firefox-evil)
#+end_src


** perspective-exwm-mode
Improve the default exwm workspace features
#+begin_src emacs-lisp
;(package! perspective )
;(package! perspective-exwm)
#+end_src
** sysmon
Sysmon for displaying system status
#+begin_src emacs-lisp
;(package! )
#+end_src
