;;; ai-backend-test.el --- gptel backend regression tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'ai)

(ert-deftest ai/llm-starintel-api-key-prefers-primary-env ()
  (let ((process-environment (copy-sequence process-environment)))
    (setenv "STARINTEL_LLM_API_KEY" "primary-key")
    (setenv "LLM_STARINTEL_API_KEY" "fallback-key")
    (should (equal (ai/llm--api-key 'starintel) "primary-key"))))

(ert-deftest ai/llm-starintel-api-key-honors-host-override ()
  (let ((process-environment (copy-sequence process-environment))
        seen-host)
    (setenv "STARINTEL_LLM_API_KEY" nil)
    (setenv "LLM_STARINTEL_API_KEY" nil)
    (setenv "STARINTEL_LLM_HOST" "llm.internal.test")
    (cl-letf (((symbol-function 'nsa/auth-source-get)
               (lambda (&rest args)
                 (setq seen-host (plist-get args :host))
                 "auth-source-key"))
              ((symbol-function 'ai/llm--auth-source-secret)
               (lambda (_host) nil)))
      (should (equal (ai/llm--api-key 'starintel) "auth-source-key"))
      (should (equal seen-host "llm.internal.test")))))

(ert-deftest ai/llm-starintel-backend-builds-openai-compatible-request ()
  (let ((process-environment (copy-sequence process-environment))
        captured)
    (setenv "STARINTEL_LLM_HOST" "gateway.test")
    (setenv "STARINTEL_LLM_ENDPOINT" "/v1/custom-chat")
    (cl-letf (((symbol-function 'gptel-make-openai)
               (lambda (name &rest args)
                 (setq captured (cons name args))
                 'starintel-backend)))
      (should (eq (ai/llm-starintel-backend
                   :stream nil
                   :name "StarIntel Test")
                  'starintel-backend))
      (should (equal (car captured) "StarIntel Test"))
      (let ((args (cdr captured)))
        (should (equal (plist-get args :host) "gateway.test"))
        (should (equal (plist-get args :endpoint) "/v1/custom-chat"))
        (should (equal (plist-get args :protocol) "https"))
        (should (plist-member args :stream))
        (should-not (plist-get args :stream))
        (should (functionp (plist-get args :key)))
        (should (equal (plist-get args :models)
                       ai/llm-starintel-models))))))

(ert-deftest ai/llm-starintel-is-a-native-provider ()
  (let ((ai/llm--backends (make-hash-table :test #'eq))
        (calls 0))
    (cl-letf (((symbol-function 'ai/llm-starintel-backend)
               (lambda (&rest _args)
                 (setq calls (1+ calls))
                 'starintel-backend)))
      (should (eq (ai/llm-backend 'starintel) 'starintel-backend))
      (should (eq (ai/llm-backend 'starintel) 'starintel-backend))
      (should (= calls 1))
      (should (equal (ai/llm-models-for-provider 'starintel)
                     '(qwen38-27b))))))

(provide 'ai-backend-test)
;;; ai-backend-test.el ends here
