;;; ai-devlog-test.el --- Tests for ai-devlog -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'json)
(require 'ai-devlog)

(defun ai/devlog-test--count (needle file)
  (with-temp-buffer
    (insert-file-contents file)
    (goto-char (point-min))
    (let ((count 0))
      (while (search-forward needle nil t) (setq count (1+ count)))
      count)))

(ert-deftest ai/devlog-sync-writes-daily-and-rebuilds-kb ()
  (let* ((tmp (make-temp-file "ai-devlog-test-" t))
         (notes (expand-file-name "notes" tmp))
         (project (expand-file-name "project" tmp))
         (ai/devlog-kb-file (expand-file-name "cache/devlog-facts.pl" tmp))
         (process-environment (copy-sequence process-environment))
         (org-roam-directory notes)
         (org-roam-dailies-directory "daily")
         (event-gh '((provider . "github") (repo . "lost-rob0t/dotfiles")
                     (kind . "pull_request") (number . "42")
                     (title . "Ship devlog") (state . "merged")
                     (url . "https://github.com/lost-rob0t/dotfiles/pull/42")
                     (updated_at . "2026-09-20T23:00:00Z")))
         (event-tea '((provider . "forgejo") (repo . "nsaspy/dotfiles")
                      (kind . "issue") (number . "7")
                      (title . "Mirror devlog") (state . "open")
                      (url . "https://git.starintel.actor/nsaspy/dotfiles/issues/7")
                      (updated_at . "2026-09-20T22:00:00Z")))
         (event-git '((provider . "git") (repo . "project")
                      (kind . "commit") (number . "abc1234")
                      (title . "test commit") (state . "committed")
                      (url . "") (updated_at . "2026-09-20T21:00:00Z")
                      (sha . "abc123456789")))
         daily)
    (make-directory project t)
    (setenv "KB_ROAM_ROOT" notes)
    (cl-letf (((symbol-function 'ai/devlog--project-root) (lambda (&optional _) project))
              ((symbol-function 'ai/devlog--provider-repositories)
               (lambda (_)
                 '((github . ((repo . "lost-rob0t/dotfiles")))
                   (tea . ((repo . "nsaspy/dotfiles"))))))
              ((symbol-function 'ai/devlog--gh-events)
               (lambda (&rest _) (list (list event-gh) "")))
              ((symbol-function 'ai/devlog--tea-events)
               (lambda (&rest _) (list (list event-tea) "")))
              ((symbol-function 'ai/devlog--git-context)
               (lambda (&rest _)
                 (list :events (list event-git) :status "## master\n M foo.el"
                       :branch "master" :head "abc123456789" :error ""))))
      (ai/devlog-sync project 24 "Implemented typed devlog capture." 20)
      (setq daily (ai/devlog--daily-file))
      (should (file-readable-p daily))
      (should (= 1 (ai/devlog-test--count "* changlog" daily)))
      (should (= 1 (ai/devlog-test--count "* devlog" daily)))
      (should (= 3 (ai/devlog-test--count ":DEVLOG_ID:" daily)))
      (should (= 3 (ai/devlog-test--count "devlog_event(" ai/devlog-kb-file)))
      (should (= 1 (ai/devlog-test--count "Session note: Implemented typed devlog capture." daily)))
      (ai/devlog-sync project 24 "Second sync." 20)
      (should (= 3 (ai/devlog-test--count ":DEVLOG_ID:" daily)))
      (should (= 2 (ai/devlog-test--count ":PROJECT_ROOT:" daily))))
    (delete-directory tmp t)))

(ert-deftest ai/devlog-prolog-query-summary ()
  (skip-unless (executable-find "swipl"))
  (let* ((tmp (make-temp-file "ai-devlog-query-" t))
         (notes (expand-file-name "notes" tmp))
         (daily (expand-file-name "daily/2026-09-20.org" notes))
         (ai/devlog-kb-file (expand-file-name "cache/devlog-facts.pl" tmp))
         (process-environment (copy-sequence process-environment))
         (org-roam-directory notes)
         (org-roam-dailies-directory "daily"))
    (make-directory (file-name-directory daily) t)
    (with-temp-file daily
      (insert "#+TITLE: fixture\n\n* changlog\n")
      (insert "** [github] lost-rob0t/dotfiles · PR #4 · Test\n")
      (insert ":PROPERTIES:\n:DEVLOG_ID: id4\n:DEVLOG_RUN_ID: run4\n")
      (insert ":PROVIDER: github\n:REPOSITORY: lost-rob0t/dotfiles\n:KIND: pull_request\n")
      (insert ":NUMBER: 4\n:STATE: merged\n:UPDATED_AT: 2026-09-20T20:00:00Z\n")
      (insert ":URL: https://example.test/4\n:END:\n"))
    (setenv "KB_ROAM_ROOT" notes)
    (let* ((json-object-type 'alist)
           (json-array-type 'list)
           (summary (json-read-from-string (ai/devlog-query "summary" nil 20))))
      (should (= 1 (alist-get 'events summary)))
      (should (equal '("github") (alist-get 'providers summary))))
    (delete-directory tmp t)))

(provide 'ai-devlog-test)
;;; ai-devlog-test.el ends here
