;;; migrate.el --- One-time native desktop source migration -*- lexical-binding: t; -*-
;; Not a runtime dependency. Never execute the legacy package installer.
(require 'cl-lib)
(require 'subr-x)
(require 'org)
(require 'ob-tangle)
(require 'json)
(require 'pp)
(defvar star-port-modules nil)
(defvar star-port-current-module nil)
(defvar star-port-packages nil)
(defvar star-port-package-sources nil)
(defvar star-port-source nil)
(defconst star-port-renames
  '((doom-leader-map . star-leader-map)
    (doom-after-init-hook . star-after-init-hook)
    (doom-theme . star-theme)
    (doom/reload . star-config-reload)
    (doom/window-maximize-buffer . delete-other-windows)
    (+popup-display-buffer-stacked-side-window-fn . display-buffer-in-side-window)
    (+org-capture-notes-file . star-capture-notes-file)
    (+org-capture-todo-file . star-capture-todo-file)
    (+org-capture-project-todo-file . star-capture-project-todo-file)
    (+org-capture-project-notes-file . star-capture-project-notes-file)
    (+org-capture-project-changelog-file . star-capture-project-changelog-file)
    (+org-capture-central-project-todo-file . star-capture-central-project-todo-file)
    (+org-capture-central-project-notes-file . star-capture-central-project-notes-file)
    (+org-capture-central-project-changelog-file . star-capture-central-project-changelog-file)))

(defun star-port-unquote (value)
  (if (memq (car-safe value) '(quote function)) (cadr value) value))

(defun star-port-read-string (text)
  (with-temp-buffer
    (insert text)
    (emacs-lisp-mode)
    (goto-char (point-min))
    (let (forms)
      (while (progn (forward-comment (point-max)) (not (eobp)))
        (push (read (current-buffer)) forms))
      (nreverse forms))))

(defun star-port-read-file (file)
  (with-temp-buffer (insert-file-contents file) (star-port-read-string (buffer-string))))

(defun star-port-module-p (args)
  (let* ((explicit (keywordp (car args)))
         (category (if explicit (car args) (car star-port-current-module)))
         (name (if explicit (cadr args) (cadr star-port-current-module)))
         (flags (if explicit (cddr args) args))
         (entry (cl-find-if (lambda (item) (and (eq (car item) category)
                                               (eq (cadr item) name))) star-port-modules)))
    (and entry (cl-every (lambda (flag) (memq flag (caddr entry))) flags))))

(defun star-port-test (form)
  "Evaluate only pure conditions in upstream package declarations."
  (cond
   ((memq form '(nil t)) form)
   ((and (symbolp form) (string-match "\\`EMACS\\([0-9]+\\)[+]\\'" (symbol-name form)))
    (>= 31 (string-to-number (match-string 1 (symbol-name form)))))
   ((symbolp form)
    (pcase form ('IS-LINUX t) ((or 'IS-MAC 'IS-WINDOWS 'IS-BSD) nil)
      ('emacs-major-version 31) ('emacs-version "31.1")
      (_ (error "Unsupported declaration constant: %S" form))))
   ((not (consp form)) form)
   (t
    (pcase (car form)
      ('quote (cadr form))
      ((or 'modulep! 'featurep!) (star-port-module-p (cdr form)))
      ('and (cl-every #'star-port-test (cdr form)))
      ('or (cl-some #'star-port-test (cdr form)))
      ('not (not (star-port-test (cadr form))))
      ('featurep
       (if (eq (cadr form) :system)
           (memq (star-port-unquote (caddr form)) '(linux unix))
         (featurep (star-port-unquote (cadr form)))))
      ('fboundp (fboundp (star-port-unquote (cadr form))))
      ('boundp (boundp (star-port-unquote (cadr form))))
      ((or '>= '> '< '<= '= 'eq 'equal 'version< 'version<=)
       (apply (car form) (mapcar #'star-port-test (cdr form))))
      (_ (error "Unsupported package condition: %S" form))))))

(defun star-port-declaration (form)
  "Collect selected declarations without executing recipe build hooks."
  (when (consp form)
    (pcase (car form)
      ('package!
       (let ((name (cadr form)) (properties (cddr form)))
         (unless (symbolp name) (error "Non-symbol package name: %S" form))
         (if (plist-get properties :disable)
             (setq star-port-packages (assq-delete-all name star-port-packages))
           (let ((merged (copy-sequence (alist-get name star-port-packages))))
             (while properties
               (let ((key (pop properties)) (value (pop properties)))
                 (setq merged (plist-put merged key value))))
             (setf (alist-get name star-port-packages) merged)
             (cl-pushnew star-port-source (alist-get name star-port-package-sources)
                         :test #'equal)))))
      ('progn (mapc #'star-port-declaration (cdr form)))
      ('when (when (star-port-test (cadr form)) (mapc #'star-port-declaration (cddr form))))
      ('unless (unless (star-port-test (cadr form)) (mapc #'star-port-declaration (cddr form))))
      ('if (if (star-port-test (cadr form)) (star-port-declaration (caddr form))
             (mapc #'star-port-declaration (cdddr form))))
      ('cond
       (let ((clause (cl-find-if (lambda (item) (star-port-test (car item))) (cdr form))))
         (mapc #'star-port-declaration (cdr clause))))
      ('unpin!
       (dolist (name (cdr form))
         (setf (alist-get name star-port-packages)
               (plist-put (alist-get name star-port-packages) :pin nil))))
      (_ (error "Unsupported upstream declaration form: %S" (car form))))))

(defun star-port-after (feature body)
  (setq feature (star-port-unquote feature))
  (cond ((null feature) `(progn ,@body))
        ((symbolp feature) `(with-eval-after-load ',feature ,@body))
        ((eq (car feature) 'or)
         (error "Disjunctive after! requires native review: %S" feature))
        (t (let ((features (if (eq (car feature) 'and) (cdr feature) feature)))
             (star-port-after (car features)
                              (list (star-port-after (cdr features) body)))))))

(defun star-port-rename-tree (form)
  (cond ((symbolp form) (or (cdr (assq form star-port-renames)) form))
        ((consp form) (cons (star-port-rename-tree (car form))
                           (star-port-rename-tree (cdr form))))
        ((vectorp form) (vconcat (mapcar #'star-port-rename-tree form)))
        (t form)))

(defun star-port-map (items &optional context)
  "Lower actual map! forms into ordinary General bindings."
  (let ((ctx (copy-sequence context)) (forms nil) (description nil))
    (while items
      (let ((item (pop items)))
        (cond
         ((consp item) (setq forms (append forms (star-port-map item ctx))))
         ((stringp item)
          (unless items (error "Key without binding: %s" item))
          (let* ((definition (star-port-normalize (pop items)))
                 (leader (plist-get ctx :leader))
                 (local (plist-get ctx :localleader))
                 (map (if leader 'star-leader-map (or (plist-get ctx :map) 'global)))
                 (prefix (or (plist-get ctx :prefix) ""))
                 (key (string-join (delq nil (list (unless (string-empty-p prefix) prefix) item)) " "))
                 (states (or (plist-get ctx :states) '(normal visual motion)))
                 (spec (if description `(list :def ,definition :which-key ,description) definition))
                 (binding
                  (cond
                   (leader `(general-define-key :keymaps ',map ,key ,spec))
                   (local `(progn
                             (general-define-key :states ',states :keymaps ',map
                                                 :prefix "SPC m" ,key ,spec)
                             (general-define-key :states '(insert emacs) :keymaps ',map
                                                 :prefix "C-c m" ,key ,spec)))
                   (t `(general-define-key ,@(when (plist-get ctx :states) `(:states ',states))
                                          :keymaps ',map ,key ,spec)))))
            (when (plist-get ctx :after)
              (setq binding (star-port-after (plist-get ctx :after) (list binding))))
            (setq forms (append forms (list binding)) description nil)))
         ((eq item :leader) (setq ctx (plist-put (plist-put ctx :leader t) :localleader nil)))
         ((eq item :localleader) (setq ctx (plist-put (plist-put ctx :localleader t) :leader nil)))
         ((eq item :map) (setq ctx (plist-put ctx :map (star-port-unquote (pop items)))))
         ((eq item :after) (setq ctx (plist-put ctx :after (star-port-unquote (pop items)))))
         ((eq item :desc) (setq description (pop items)))
         ((memq item '(:prefix :prefix-map))
          (let ((prefix (pop items)))
            (setq ctx (plist-put ctx :prefix
                                (string-join (delq nil (list (plist-get ctx :prefix)
                                                            (if (consp prefix) (car prefix) prefix))) " ")))))
         ((and (keywordp item) (string-match-p "\\`:[nivmeor]+\\'" (symbol-name item)))
          (setq ctx (plist-put ctx :states
                              (mapcar (lambda (ch) (cdr (assq ch '((?n . normal) (?i . insert)
                                                                  (?v . visual) (?m . motion)
                                                                  (?e . emacs) (?o . operator)
                                                                  (?r . replace)))))
                                      (string-to-list (substring (symbol-name item) 1))))))
         (t (error "Unsupported map! item: %S" item)))))
    forms))

(defun star-port-normalize (form)
  (cond
   ((atom form) (star-port-rename-tree form))
   ((memq (car form) '(quote function))
    (if (and (eq (car form) 'function) (eq (car-safe (cadr form)) 'lambda))
        `(function ,(star-port-normalize (cadr form)))
      (star-port-rename-tree form)))
   ((eq (car form) 'after!)
    (star-port-after (cadr form) (mapcar #'star-port-normalize (cddr form))))
   ((eq (car form) 'map!) `(progn ,@(star-port-map (cdr form))))
   ((eq (car form) 'setq!) (star-port-normalize (cons 'setq (cdr form))))
   ((eq (car form) 'use-package!) (star-port-normalize (cons 'use-package (cdr form))))
   ((eq (car form) 'use-package)
    (let ((name (if (eq (cadr form) 'flashcards) 'flashcard (cadr form)))
          (args (cddr form)) (result nil))
      (while args
        (let ((arg (pop args)))
          (cond ((memq arg '(:ensure :straight)) (pop args))
                ((and (eq arg :after) (eq (star-port-unquote (car args)) name)) (pop args))
                (t (push (star-port-normalize arg) result)))))
      `(use-package ,name ,@(nreverse result))))
   ((eq (car form) 'add-hook!)
    (unless (= (length form) 3) (error "Review nontrivial add-hook!: %S" form))
    `(add-hook ,@(mapcar #'star-port-normalize (cdr form))))
   ((eq (car form) 'set-file-template!)
    `(star-set-file-template ,@(mapcar #'star-port-normalize (cdr form))))
   ((eq (car form) 'set-company-backend!)
    `(add-hook ',(intern (concat (symbol-name (star-port-unquote (cadr form))) "-hook"))
               (lambda () (setq-local company-backends (list ,@(cddr form))))))
   ((and (eq (car form) 'defun) (memq (cadr form) '(nsa/config-sync doom-config-sync)))
    `(defalias ',(cadr form) #'star-config-sync))
   ((and (eq (car form) 'setq) (eq (cadr form) 'org-configs-list))
    '(setq org-configs-list (star-config-source-files)))
   ((eq (car form) 'org-babel-do-load-languages)
    `(star-enable-babel-languages ,(star-port-normalize (caddr form))))
   ((proper-list-p form) (mapcar #'star-port-normalize form))
   (t (cons (star-port-normalize (car form)) (star-port-normalize (cdr form))))))

(defun star-port-text (text)
  "Transform code retaining top-level comments and autoload cookies."
  (with-temp-buffer
    (insert text)
    (emacs-lisp-mode)
    (goto-char (point-min))
    (let ((result "") (previous (point-min)))
      (while (progn (forward-comment (point-max)) (not (eobp)))
        (setq result (concat result (buffer-substring-no-properties previous (point))))
        (let ((form (read (current-buffer))))
          (setq result (concat result (pp-to-string (star-port-normalize form)))))
        (setq previous (point)))
      (concat result (buffer-substring-no-properties previous (point-max))))))

(defun star-port-write-org (file title blocks)
  (with-temp-file file
    (insert "#+TITLE: " title "\n#+STARTUP: overview\n"
            "#+PROPERTY: header-args:emacs-lisp :comments no :padline yes :mkdirp yes\n\n"
            "The active code below is ordinary Emacs Lisp. Doom is not loaded.\n"
            "One time a human wrote this. The parentheses remember.\n\n")
    (dolist (block blocks)
      (insert "* " (car block) "\n#+begin_src emacs-lisp :tangle " (cadr block) "\n"
              (caddr block) "\n#+end_src\n\n")))
  (org-babel-tangle-file file))

(defun star-port-generate (root)
  (let* ((default-directory (file-name-as-directory root))
         (target (expand-file-name "emacs/desktop/"))
         (core (getenv "DOOM_AUDIT_CORE"))
         (module-root (getenv "DOOM_AUDIT_MODULES"))
         (init (cl-find-if (lambda (f) (eq (car-safe f) 'doom!))
                           (star-port-read-file ".doom.d/init.el")))
         (category nil) (personal nil) (autoloads nil))
    (unless (and core module-root init) (error "Missing pinned baseline inputs"))
    (setq star-port-modules nil star-port-packages nil star-port-package-sources nil)
    (dolist (entry (cdr init))
      (if (keywordp entry) (setq category entry)
        (push (list category (if (consp entry) (car entry) entry)
                    (and (consp entry) (cdr entry))) star-port-modules)))
    (setq star-port-modules (nreverse star-port-modules))
    (let ((star-port-source "doom-core/modules/doom/packages.el"))
      (mapc #'star-port-declaration
            (star-port-read-file (expand-file-name "modules/doom/packages.el" core))))
    (dolist (module star-port-modules)
      (let ((star-port-current-module module)
            (file (expand-file-name
                   (format "modules/%s/%s/packages.el"
                           (substring (symbol-name (car module)) 1) (cadr module)) module-root)))
        (when (file-exists-p file)
          (let ((star-port-source (file-relative-name file module-root)))
            (mapc #'star-port-declaration (star-port-read-file file))))))
    (dolist (form (star-port-read-file ".doom.d/packages.el"))
      (when (memq (car-safe form) '(package! unpin!))
        (let ((star-port-source ".doom.d/packages.org")) (star-port-declaration form))))
    (let* ((extras '(general smartparens projectile better-jumper dtrt-indent ws-butler
                    org-super-agenda ob-graphql dap-mode js2-mode rjsx-mode git-gutter
                    git-gutter-fringe org-appear))
           (names (sort (delete-dups (append extras (mapcar #'car star-port-packages)))
                        (lambda (a b) (string< (symbol-name a) (symbol-name b))))))
      (with-temp-file (expand-file-name "packages.org" target)
        (insert "#+TITLE: Native desktop package inventory\n#+STARTUP: overview\n\n"
                "* Ownership\nNix owns package installation and dependency resolution. Startup never runs\n"
                "a package installer. This baseline includes selected Doom core/modules,\n"
                "private declarations, and explicitly retained legacy-core/native dependencies.\n"
                "It is not an inventory of the old machine's unobserved installed closure.\n\n"
                "One time a human wrote this. A dependency arrived and nobody told the human.\n\n"
                "* Manifest\n#+begin_src json :tangle packages.json :comments no\n"
                (json-encode
                 `((schema . "star-emacs.packages.v1")
                   (doom_core . "01d68aaf6bd7db073365385cd82e1ad7e815295c")
                   (doom_modules . "d57ab52a3425b6d39564fb011b0e9571da0e270f")
                   (historical_installation_verified . :json-false)
                   (packages . ,(vconcat (mapcar #'symbol-name names)))
                   (declarations . ,(vconcat
                                    (mapcar (lambda (name)
                                              `((name . ,(symbol-name name))
                                                (sources . ,(vconcat (or (alist-get name star-port-package-sources)
                                                                        '("native/legacy-core-retained"))))
                                                (properties . ,(prin1-to-string (alist-get name star-port-packages)))))
                                            names)))))
                "\n#+end_src\n"))
      (org-babel-tangle-file (expand-file-name "packages.org" target))
      (princ (format "SELECTED-PACKAGES %S\n" names)))
    (push (list "File header" "personal.el" ";;; personal.el --- Personal configuration -*- lexical-binding: t; -*-") personal)
    (org-babel-map-src-blocks ".doom.d/config.org"
      (let* ((info (org-babel-get-src-block-info 'light))
             (language (nth 0 info)) (body (nth 1 info))
             (tangle (cdr (assq :tangle (nth 2 info)))))
        (when (and (equal language "emacs-lisp")
                   (not (member tangle '("no" "./init.el" "init.el")))
                   (not (org-in-commented-heading-p)))
          (push (list (or (car (last (org-get-outline-path t))) "Personal settings")
                      "personal.el" (star-port-text body)) personal))))
    (star-port-write-org (expand-file-name "personal.org" target)
                         "Personal desktop Emacs configuration" (nreverse personal))
    (dolist (file (directory-files ".doom.d/autoload" t "\\.el\\'"))
      (let* ((base (file-name-base file))
             (name (if (member base '("llm" "starintel")) (concat "star-autoload-" base) base))
             (text (with-temp-buffer (insert-file-contents file) (buffer-string))))
        (push (list base (concat "autoload/" name ".el") (star-port-text text)) autoloads)))
    (star-port-write-org (expand-file-name "autoloads.org" target)
                         "Desktop integration autoloads" (nreverse autoloads))
    (require 'loaddefs-gen)
    (loaddefs-generate (expand-file-name "autoload" target)
                      (expand-file-name "star-autoloads.el" target))
    (dolist (file (directory-files-recursively target "\\.el\\'"))
      (with-temp-buffer (insert-file-contents file) (emacs-lisp-mode) (check-parens)))
    (princ "Generated native Org/Lisp; check-parens passed.\n")))

(when (getenv "STAR_PORT_GENERATE") (star-port-generate default-directory))
(provide 'star-port-migrate)
