:- use_module(library(aggregate)).
:- use_module(library(http/json)).
:- use_module(library(lists)).
:- use_module(library(pcre)).

:- dynamic roam_file/9.
:- dynamic roam_tag/2.
:- dynamic roam_heading/5.
:- dynamic roam_link/2.

generic_tag(ai). generic_tag(misc). generic_tag(note). generic_tag(notes).
generic_tag(general). generic_tag(stuff). generic_tag(thing). generic_tag(things).
generic_tag(todo). generic_tag(todos). generic_tag(kb).

sensitive_tag(secret). sensitive_tag(credential). sensitive_tag(credentials).
sensitive_tag(private_key). sensitive_tag(token).

reset_kb :-
    retractall(roam_file(_,_,_,_,_,_,_,_,_)),
    retractall(roam_tag(_,_)),
    retractall(roam_heading(_,_,_,_,_)),
    retractall(roam_link(_,_)).

value_atom(Value, Atom) :-
    ( atom(Value) -> Atom = Value
    ; string(Value) -> atom_string(Atom, Value)
    ; number(Value) -> atom_number(Atom, Value)
    ; term_to_atom(Value, Atom)
    ).

dict_atom(Dict, Key, Atom) :-
    ( get_dict(Key, Dict, Value) -> value_atom(Value, Atom)
    ; Atom = ''
    ).

load_manifest(Path) :-
    reset_kb,
    setup_call_cleanup(open(Path, read, In), json_read_dict(In, Manifest), close(In)),
    maplist(assert_file, Manifest.files).

assert_file(D) :-
    dict_atom(D, id, Id), dict_atom(D, path, Path), dict_atom(D, title, Title),
    dict_atom(D, kind, Kind), dict_atom(D, visibility, Visibility),
    dict_atom(D, schema, Schema), (D.ai_generated == true -> Ai = true ; Ai = false),
    dict_atom(D, ai_tag, AiTag), dict_atom(D, censor_profile, Censor),
    assertz(roam_file(Id, Path, Title, Kind, Visibility, Schema, Ai, AiTag, Censor)),
    forall(member(Tag0, D.tags), (term_string(Tag0, TS), atom_string(Tag, TS), assertz(roam_tag(Id, Tag)))),
    forall(member(H, D.headings), assert_heading(Id, H)),
    forall(member(L0, D.links), (term_string(L0, LS), atom_string(Link, LS), assertz(roam_link(Id, Link)))).

assert_heading(FileId, H) :-
    dict_atom(H, id, HeadingId), dict_atom(H, title, Title),
    dict_atom(H, visibility, Visibility), Level = H.level,
    assertz(roam_heading(FileId, HeadingId, Level, Title, Visibility)).

topical_tag(FileId, Tag) :-
    roam_tag(FileId, Tag), \+ generic_tag(Tag), \+ memberchk(Tag, [private,noexport]),
    \+ sub_atom(Tag, 0, 3, _, 'ai_').

topical_count(FileId, Count) :-
    setof(Tag, topical_tag(FileId, Tag), Tags), !, length(Tags, Count).
topical_count(_, 0).

valid_ai_tag(Tag) :- atom(Tag), re_match('^ai_[a-z0-9]{12,}$', Tag).

violation(Path, bad_schema(Schema)) :-
    roam_file(_, Path, _, _, public, Schema, _, _, _), Schema \= 'org-roam-meta/v1'.
violation(Path, missing_kind) :-
    roam_file(_, Path, _, '', public, _, _, _, _).
violation(Path, too_few_topical_tags(Count)) :-
    roam_file(Id, Path, _, _, public, _, _, _, _), topical_count(Id, Count), Count < 2.
violation(Path, missing_ai_tag) :-
    roam_file(_, Path, _, _, _, _, true, AiTag, _), \+ valid_ai_tag(AiTag).
violation(Path, ai_tag_not_in_filetags(AiTag)) :-
    roam_file(Id, Path, _, _, _, _, true, AiTag, _), valid_ai_tag(AiTag), \+ roam_tag(Id, AiTag).
violation(Path, duplicate_ai_tag(AiTag)) :-
    roam_file(_, Path, _, _, _, _, true, AiTag, _), valid_ai_tag(AiTag),
    aggregate_all(count, roam_file(_, _, _, _, _, _, true, AiTag, _), N), N > 1.
violation(Path, sensitive_public_tag(Tag)) :-
    roam_file(Id, Path, _, _, public, _, _, _, strict), roam_tag(Id, Tag), sensitive_tag(Tag).

publishable_file(Path) :-
    roam_file(_, Path, _, _, public, _, _, _, _), \+ violation(Path, _).

emit_kb(Path) :-
    setup_call_cleanup(
        open(Path, write, Out),
        ( format(Out, '%% generated by roam-censor; do not edit~n', []),
          forall(roam_file(A,B,C,D,E,F,G,H,I), write_term(Out, roam_file(A,B,C,D,E,F,G,H,I), [quoted(true), fullstop(true), nl(true)])),
          forall(roam_tag(A,B), write_term(Out, roam_tag(A,B), [quoted(true), fullstop(true), nl(true)])),
          forall(roam_heading(A,B,C,D,E), write_term(Out, roam_heading(A,B,C,D,E), [quoted(true), fullstop(true), nl(true)])),
          forall(roam_link(A,B), write_term(Out, roam_link(A,B), [quoted(true), fullstop(true), nl(true)]))
        ), close(Out)).

print_violations(Vs) :-
    forall(member(Path-Reason, Vs), format(user_error, 'roam-censor: ~w: ~q~n', [Path, Reason])).

run(check, Manifest, KbOut) :-
    load_manifest(Manifest),
    findall(Path-Reason, violation(Path, Reason), V0), sort(V0, Vs), emit_kb(KbOut),
    ( Vs == [] -> aggregate_all(count, publishable_file(_), N), format('roam-censor: OK (~d publishable files)~n', [N])
    ; print_violations(Vs), halt(2) ).
run(build, Manifest, KbOut) :- load_manifest(Manifest), emit_kb(KbOut), format('roam-censor: wrote ~w~n', [KbOut]).
run('self-test', _, _) :-
    reset_kb,
    assertz(roam_file(a, 'good.org', 'Good', note, public, 'org-roam-meta/v1', true, ai_123456789abc, strict)),
    assertz(roam_tag(a, prolog)), assertz(roam_tag(a, org_roam)), assertz(roam_tag(a, ai_123456789abc)),
    ( violation('good.org', _) -> halt(3) ; true ),
    format('roam-censor self-test: OK~n', []).

main :-
    current_prolog_flag(argv, Argv),
    ( Argv = [Mode0, Manifest, KbOut|_] -> value_atom(Mode0, Mode), run(Mode, Manifest, KbOut)
    ; format(user_error, 'usage: roam-censor.pl check|build MANIFEST KBOUT~n', []), halt(2) ).

:- initialization(main, main).
