backend = "xrender";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.75;

fading = false;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true;
unredir-if-possible = false;

opacity-rule = [
  "80:class_g = 'Emacs'"
];

shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Conky'",
  "class_g = 'flameshot'",
  "name = 'flameshot'",
  "_GTK_FRAME_EXTENTS"
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.9; focus = true; full-shadow = false; };
  dock = { shadow = false; opacity = 1.0; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.9; };
  dropdown_menu = { opacity = 0.9; };
};
