;;; star-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from autoload/activity-watch.el

(defvar activity-watch-mode nil "\
Non-nil when ActivityWatch is enabled in the current buffer.")
(defvar global-activity-watch-mode nil "\
Non-nil when ActivityWatch is enabled globally.")


;;; Generated autoloads from autoload/chatgpt-books.el

(autoload '+chatgpt-books/load "autoload/chatgpt-books" "\
Load the project-local chatgpt-books Emacs package.

Dotfiles owns only checkout discovery and package loading.  The books
repository owns its Org-roam database, capture templates, export behavior,
and project-specific settings." t)
(autoload '+chatgpt-books/open "autoload/chatgpt-books" "\
Load chatgpt-books and open its project landing page." t)
(register-definition-prefixes "autoload/chatgpt-books" '("+chatgpt-books-"))


;;; Generated autoloads from autoload/dired-dirvish.el

(with-eval-after-load 'dired (setq dired-listing-switches "-l --almost-all --human-readable --group-directories-first --no-group" dired-dwim-target t dired-recursive-copies 'always dired-recursive-deletes 'top delete-by-moving-to-trash t) (when (boundp 'dired-kill-when-opening-new-dired-buffer) (setq dired-kill-when-opening-new-dired-buffer t)) (when (boundp 'dired-mouse-drag-files) (setq dired-mouse-drag-files t)))
(setq dirvish-attributes '(subtree-state file-time file-size) dirvish-side-attributes '(file-size) dirvish-default-layout nil dirvish-mode-line-format '(:left (sort symlink) :right (omit yank index)) dirvish-preview-dispatchers '(image gif archive pdf) dirvish-preview-buffers-max-count 2 dirvish-preview-large-file-threshold (* 256 1024) dirvish-large-directory-threshold (and (executable-find "fd") 10000))
(autoload 'dirvish-override-dired-mode "dirvish" nil t)
(dirvish-override-dired-mode)
(with-eval-after-load 'dirvish (setq dirvish-quick-access-entries '(("h" "~/" "Home") ("d" "~/Downloads/" "Downloads") ("s" "/mnt/share" "Share Drive") ("t" "~/.local/share/Trash/files/" "TrashCan"))) (global-set-key (kbd "C-c f") #'dirvish-fd) (define-key dirvish-mode-map (kbd "?") #'dirvish-dispatch) (define-key dirvish-mode-map (kbd "a") #'dirvish-quick-access) (define-key dirvish-mode-map (kbd "f") #'dirvish-file-info-menu) (define-key dirvish-mode-map (kbd "y") #'dirvish-yank-menu) (define-key dirvish-mode-map (kbd "N") #'dirvish-narrow) (define-key dirvish-mode-map (kbd "^") #'dirvish-history-last) (define-key dirvish-mode-map (kbd "h") #'dirvish-history-jump) (define-key dirvish-mode-map (kbd "s") #'dirvish-quicksort) (define-key dirvish-mode-map (kbd "v") #'dirvish-vc-menu) (define-key dirvish-mode-map (kbd "TAB") #'dirvish-subtree-toggle) (define-key dirvish-mode-map (kbd "M-f") #'dirvish-history-go-forward) (define-key dirvish-mode-map (kbd "M-b") #'dirvish-history-go-backward) (define-key dirvish-mode-map (kbd "M-l") #'dirvish-ls-switches-menu) (define-key dirvish-mode-map (kbd "M-m") #'dirvish-mark-menu) (define-key dirvish-mode-map (kbd "M-t") #'dirvish-layout-toggle) (define-key dirvish-mode-map (kbd "M-s") #'dirvish-setup-menu) (define-key dirvish-mode-map (kbd "M-e") #'dirvish-emerge-menu) (define-key dirvish-mode-map (kbd "M-j") #'dirvish-fd-jump))


;;; Generated autoloads from autoload/gpt-todos.el

(autoload 'gpt-todos-sync "autoload/gpt-todos" "\
Run gpt-todos sync asynchronously.
When FILE is non-nil, preserve and synchronize that just-saved agenda file.

(fn &optional FILE)" t)
(autoload 'gpt-todos-sync-after-save "autoload/gpt-todos" "\
Synchronize a just-saved Org file when it belongs to the live agenda tree.")
(add-hook 'after-save-hook #'gpt-todos-sync-after-save)
(register-definition-prefixes "autoload/gpt-todos" '("gpt-todos-"))


;;; Generated autoloads from autoload/org-agenda-compat.el

(with-eval-after-load 'org-super-agenda (put 'org-super-agenda-groups 'custom-type 'sexp))


;;; Generated autoloads from autoload/research-approval.el

(autoload 'nsa/research-approve-and-push "autoload/research-approval" "\
Record APPROVED for the current canonical research record and push it." t)
(autoload 'nsa/research-reject-and-push "autoload/research-approval" "\
Record REJECTED for the current canonical research record and push it." t)
(register-definition-prefixes "autoload/research-approval" '("nsa/research-approval--"))


;;; Generated autoloads from autoload/research-dashboard.el

(autoload 'nsa/research-dashboard "autoload/research-dashboard" "\
Show open research across GitHub without blocking Emacs." t)
(register-definition-prefixes "autoload/research-dashboard" '("nsa/research-dashboard-"))


;;; Generated autoloads from autoload/research-dashboard-evil.el

(autoload 'nsa/research-dashboard-evil-setup "autoload/research-dashboard-evil" "\
Make research dashboard controls work directly in Evil command states.")
(add-hook 'nsa/research-dashboard-mode-hook #'nsa/research-dashboard-evil-setup)
(register-definition-prefixes "autoload/research-dashboard-evil" '("nsa/research-dashboard-evil--"))


;;; Generated autoloads from autoload/research-dashboard-local.el

(autoload 'nsa/research-dashboard-local-add-directory "autoload/research-dashboard-local" "\
Add DIRECTORY to the research dashboard's local sources and refresh.

(fn DIRECTORY)" t)
(autoload 'nsa/research-dashboard-local-remove-directory "autoload/research-dashboard-local" "\
Remove DIRECTORY from the research dashboard's local sources and refresh.

(fn DIRECTORY)" t)
(autoload 'nsa/research-dashboard-local-setup "autoload/research-dashboard-local" "\
Install local checkout support in the current research dashboard buffer.")
(add-hook 'nsa/research-dashboard-mode-hook #'nsa/research-dashboard-local-setup)
(register-definition-prefixes "autoload/research-dashboard-local" '("nsa/research-dashboard-local-"))


;;; Generated autoloads from autoload/research-dashboard-local-defaults.el

(setq nsa/research-dashboard-local-checkouts (list (expand-file-name "~/starintel") (expand-file-name "~/Documents/Projects/prolog-rlm")))
(with-eval-after-load 'research-dashboard (require 'research-dashboard-local) (require 'research-dashboard-local-dwim))


;;; Generated autoloads from autoload/research-dashboard-local-dwim.el

(add-hook 'nsa/research-dashboard-mode-hook #'nsa/research-dashboard-local-dwim--install)
(register-definition-prefixes "autoload/research-dashboard-local-dwim" '("nsa/research-dashboard-local-dwim--"))


;;; Generated autoloads from autoload/screen-capture.el

(autoload 'screen-capture-record "autoload/screen-capture" "\
Prompt quickly for MODE and destination, then start recording asynchronously.

(fn &optional MODE)" t)
(autoload 'screen-capture-stop "autoload/screen-capture" "\
Stop and finalize the current screen recording." t)
(register-definition-prefixes "autoload/screen-capture" '("screen-capture-"))


;;; Generated autoloads from autoload/star-autoload-llm.el

(autoload #'ai/chat "chat" "\
Create and open a persistent Org agent chat." t)
(autoload #'ai/meme-generate "meme" "\
Generate a meme from a region or prompt." t)
(autoload #'ai/youtube-context "youtube-context" "\
Fetch YouTube context asynchronously." t)
(autoload #'ai/prompt-menu "ai-prompts" "\
Open reusable prompt and image commands." t)
(autoload #'ai/image-generate "ai-image" "\
Generate an image with OpenAI's image tool." t)
(autoload #'ai/image-generate-template "ai-image" "\
Generate an image from a reusable prompt template." t)
(autoload #'ai/image-edit "ai-image" "\
Edit an image with OpenAI's image tool." t)
(autoload #'mara "mara" "\
Open the local Mara runtime." t)
(autoload #'seductress "gptel-personas" "\
Open a dedicated Seductress gptel chat." t)
(autoload '+llm/bind-keys "autoload/star-autoload-llm" "\
Bind the local LLM entrypoints after Doom finishes loading.")
(add-hook 'star-after-init-hook #'+llm/bind-keys)
(with-eval-after-load 'gptel (run-at-time 0 nil (lambda nil (require 'ai-init) (require 'gptel-personas) (ai/llm-apply-defaults) (ai/gptel-apply-directives))))
(autoload '+llm/load "autoload/star-autoload-llm" "\
Load the complete local LLM configuration." t)
(autoload '+llm/mcp-connect-all "autoload/star-autoload-llm" "\
Start configured MCP servers and register their tools with gptel.

(fn &optional NOERROR)" t)
(autoload '+llm/proxmox-register "autoload/star-autoload-llm" "\
Register the Proxmox MCP server.

(fn &optional NOERROR)" t)
(autoload '+llm/unifi-register "autoload/star-autoload-llm" "\
Register the UDM Pro / UniFi MCP server.

(fn &optional NOERROR)" t)
(autoload '+llm/discord-register "autoload/star-autoload-llm" "\
Register the Discord MCP server.

(fn &optional NOERROR)" t)
(autoload '+llm/proxmox-connect "autoload/star-autoload-llm" "\
Connect the Proxmox MCP server." t)
(autoload '+llm/unifi-connect "autoload/star-autoload-llm" "\
Connect the UDM Pro / UniFi MCP server." t)
(autoload '+llm/discord-connect "autoload/star-autoload-llm" "\
Connect the Discord MCP server." t)
(autoload '+llm/chat "autoload/star-autoload-llm" "\
Open a persistent Org gptel agent chat." t)
(autoload '+llm/youtube-context "autoload/star-autoload-llm" "\
Fetch a video transcript asynchronously and copy it as LLM context." t)
(autoload '+llm/prompt-menu "autoload/star-autoload-llm" "\
Open the reusable prompt-template and image-generation menu." t)
(autoload '+llm/image-generate "autoload/star-autoload-llm" "\
Generate an image from the active region or a minibuffer prompt." t)
(autoload '+llm/image-generate-template "autoload/star-autoload-llm" "\
Generate an image from a reusable prompt template." t)
(autoload '+llm/image-edit "autoload/star-autoload-llm" "\
Edit an image using OpenAI's image-generation tool." t)
(autoload '+llm/use-glm-5.2 "autoload/star-autoload-llm" "\
Switch to GLM-5.2 through OpenRouter.

(fn &optional LOCAL)" t)
(autoload '+llm/use-gpt-5.6-sol "autoload/star-autoload-llm" "\
Switch to GPT-5.6 Sol through OpenRouter.

(fn &optional LOCAL)" t)
(autoload '+llm/use-gpt-luna "autoload/star-autoload-llm" "\
Switch to GPT-5.6 Luna through OpenRouter.

(fn &optional LOCAL)" t)
(autoload '+llm/use-fable "autoload/star-autoload-llm" "\
Switch to Claude Fable 5 through OpenRouter.

(fn &optional LOCAL)" t)
(autoload '+llm/use-openai-oauth "autoload/star-autoload-llm" "\
Switch to GPT-5.6 Sol through OpenAI subscription OAuth.

(fn &optional LOCAL)" t)
(autoload '+llm/openai-login "autoload/star-autoload-llm" "\
Authenticate the OpenAI subscription backend." t)
(autoload '+llm/agent-context "autoload/star-autoload-llm" "\
Toggle project instruction files in gptel context." t)
(register-definition-prefixes "autoload/star-autoload-llm" '("+llm/yt-dlp-context"))


;;; Generated autoloads from autoload/star-autoload-starintel.el

(register-definition-prefixes "autoload/star-autoload-starintel" '("nsa/starintel-"))


;;; Generated autoloads from autoload/starintel-research.el

(autoload 'star/research "autoload/starintel-research" "\
Open the Starintel research control surface." t)

;;; End of scraped data

(provide 'star-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; star-autoloads.el ends here
