(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(SETF (UIOP/OS:GETENV "WEBKIT_DISABLE_COMPOSITING_MODE") "1")
(DEFINE-CONFIGURATION PASSWORD:USER-KEEPASSXC-INTERFACE
  ((PASSWORD:PASSWORD-FILE /HOME/UNSEEN/DOCUMENTS/ENCRYPTED/PASSWORDS.KDBX)))
